public inherited sharing class OpportunityConstants {
 // -------------------------
    // Stage Names
    // -------------------------
    public static final String STAGE_PROSPECTING = 'Prospecting';
    public static final String STAGE_QUALIFICATION = 'Qualification';
    public static final String STAGE_NEEDS_ANALYSIS = 'Needs Analysis';
    public static final String STAGE_VALUE_PROPOSITION = 'Value Proposition';
    public static final String STAGE_ID_DECISION_MAKERS = 'Id. Decision Makers';
    public static final String STAGE_PERCEPTION_ANALYSIS = 'Perception Analysis';
    public static final String STAGE_PROPOSAL_PRICE_QUOTE = 'Proposal/Price Quote';
    public static final String STAGE_NEGOTIATION_REVIEW = 'Negotiation/Review';
    public static final String STAGE_CLOSED_WON = 'Closed Won';
    public static final String STAGE_CLOSED_LOST = 'Closed Lost';
}